In [31]:
import torch
import torch.optim as optim
import torch.nn as nn
from collections import OrderedDict

In [8]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]

In [9]:
t_c = torch.tensor(t_c).unsqueeze(1)
t_u = torch.tensor(t_u).unsqueeze(1)

(tensor([[ 0.5000],
         [14.0000],
         [15.0000],
         [28.0000],
         [11.0000],
         [ 8.0000],
         [ 3.0000],
         [-4.0000],
         [ 6.0000],
         [13.0000],
         [21.0000]]),
 tensor([[35.7000],
         [55.9000],
         [58.2000],
         [81.9000],
         [56.3000],
         [48.9000],
         [33.9000],
         [21.8000],
         [48.4000],
         [60.4000],
         [68.4000]]))

In [16]:
def train(epoch, t_u, t_c, model, loss_fn, optimizer):
    for i in range(epoch):
        t_p = model(t_u)
        loss = loss_fn(t_p, t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if(i%500 == 0):
            print("Epoch: {}. Loss: {}.".format(i,loss))
        

In [19]:
model = nn.Linear(1,1)
learning_rate = 1e-2
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

In [20]:
train(5000, t_u = 0.1*t_u, t_c=t_c, model = model, loss_fn=nn.MSELoss(), optimizer=optimizer)

Epoch: 0. Loss: 286.6715087890625.
Epoch: 500. Loss: 7.941466808319092.
Epoch: 1000. Loss: 3.843402862548828.
Epoch: 1500. Loss: 3.0949034690856934.
Epoch: 2000. Loss: 2.9581944942474365.
Epoch: 2500. Loss: 2.933225393295288.
Epoch: 3000. Loss: 2.928663730621338.
Epoch: 3500. Loss: 2.9278335571289062.
Epoch: 4000. Loss: 2.927680730819702.
Epoch: 4500. Loss: 2.9276514053344727.


In [22]:
list(model.parameters())

[Parameter containing:
 tensor([[5.3671]], requires_grad=True),
 Parameter containing:
 tensor([-17.3012], requires_grad=True)]

In [24]:
seq_model = nn.Sequential(
    nn.Linear(1,13),
    nn.Tanh(),
    nn.Linear(13,1)
)
seq_model

Sequential(
  (0): Linear(in_features=1, out_features=13, bias=True)
  (1): Tanh()
  (2): Linear(in_features=13, out_features=1, bias=True)
)

In [25]:
[param for param in seq_model.parameters()]

[Parameter containing:
 tensor([[ 0.9993],
         [ 0.5695],
         [ 0.9851],
         [-0.0175],
         [ 0.9257],
         [-0.2527],
         [-0.2931],
         [-0.4282],
         [ 0.1921],
         [-0.4833],
         [-0.9365],
         [ 0.2118],
         [ 0.9801]], requires_grad=True),
 Parameter containing:
 tensor([-0.1320,  0.6839, -0.1541,  0.0138,  0.8493, -0.8541,  0.9964, -0.8775,
          0.5653,  0.9459,  0.3301,  0.3360,  0.6509], requires_grad=True),
 Parameter containing:
 tensor([[ 0.2117, -0.1964, -0.0292, -0.2040,  0.0767, -0.0810, -0.1954, -0.2215,
          -0.0930, -0.2602,  0.2720, -0.2747, -0.0376]], requires_grad=True),
 Parameter containing:
 tensor([-0.1462], requires_grad=True)]

In [29]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

0.weight torch.Size([13, 1])
0.bias torch.Size([13])
2.weight torch.Size([1, 13])
2.bias torch.Size([1])


In [32]:
seq_model = nn.Sequential(OrderedDict([
('hidden_linear', nn.Linear(1, 8)),
('hidden_activation', nn.Tanh()),
('output_linear', nn.Linear(8, 1))
]))

In [33]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_linear.weight torch.Size([8, 1])
hidden_linear.bias torch.Size([8])
output_linear.weight torch.Size([1, 8])
output_linear.bias torch.Size([1])


In [37]:
seq_model.output_linear.weight

Parameter containing:
tensor([[0.2776, 0.0458, 0.0994, 0.1589, 0.1573, 0.1018, 0.1252, 0.3262]],
       requires_grad=True)

In [35]:
seq_model

Sequential(
  (hidden_linear): Linear(in_features=1, out_features=8, bias=True)
  (hidden_activation): Tanh()
  (output_linear): Linear(in_features=8, out_features=1, bias=True)
)